### ISSUE TITLE
try to make application/x-www-form-urlencoded  Request but getting failed  

### ISSUE THREAD

**Issue by Himanshu44ec06** [ForbesLindesay/sync-request#104]
Hi, I am trying to make "application/x-www-form-urlencoded"  Code is below 
    var request = require("sync-request");
    var  FormData  =  request.FormData;
    var data = new FormData();
	data.append('grant_type', 'password');
	data.append('username', 'Administrator');
	data.append('client_id', 'b7d32cdd049d436bbbd314d8d7140861');
	data.append('password', '1');

	var  tokenRequestOptions = {
		headers: { 'content-type': 'application/x-www-form-urlencoded' },
		form: data
		};

		
	var result  =  request('post','https://qa2016-pp.sotiqa.com/sotiassist/account/oauth2/token',tokenRequestOptions);

This is Working fine when  using  NPM request

Please Help

**Comment by ForbesLindesay** [comment]
looks like it should work fine to me. you haven't really given me anything specific about what's not working though. Are you running this in a browser, or on node.js? What do you mean by "NPM request"? What exactly is the error/stack trace you get out of this?

**Comment by Himanshu44ec06** [comment]
Are you running this in a browser, or on node.js? --  NODE JS
 What do you mean by "NPM request"? -- REQUEST  package

**Comment by ForbesLindesay** [comment]
I don't know at a glance why this isn't working. You shouldn't need to specify the content-type header as that should happen automatically, but without you posting some info about what is actually going wrong, it's really hard to diagnose anything.
