### ISSUE TITLE
TypeScript wrapper for your library

### ISSUE THREAD

**Issue by VeritasSoftware** [ForbesLindesay/sync-request#108]
Hi!

FYI.

I have created a **TypeScript strongly-typed wrapper** for your library.
I have exposed your library via **SyncRequestClient** and **SyncRequestService** classes.

The wrapper is available via a npm package ts-sync-request.

[**ts-sync-request**](https://www.npmjs.com/package/ts-sync-request)

**Maybe you can add a link to the package from your readme.**

## Sample Usage

**TypeScript classes**
```typescript
class Movie {
 
    constructor(public name: string, public director: string) {
 
    }    
}
 
class Search {
 
    constructor(public keywords: string) {
 
    }    
}
```

**Usage**

Install package in project:

    npm i ts-sync-request

Then

```typescript
import { SyncRequestClient } from 'ts-sync-request/dist'
```

**GET**:
```typescript
    let id = 1;
    let url = "http://localhost:59039/api/Movies/" + id;
 
    let response = new SyncRequestClient()
                                .addHeader("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NDc2OTg1MzgsIm5iZiI6MTU0NzY5NDIxOCwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6InN0cmluZyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6InN0cmluZyIsIkRPQiI6IjEvMTcvMjAxOSIsImlzcyI6InlvdXIgYXBwIiwiYXVkIjoidGhlIGNsaWVudCBvZiB5b3VyIGFwcCJ9.qxFdcdAVKG2Idcsk_tftnkkyB2vsaQx5py1KSMy3fT4")
                            .get<Movie>(url);
```

**POST**:

```typescript
    let url = "http://localhost:59039/api/Movies/search";
 
    let search = new Search("Fiction");
 
    let response = new SyncRequestClient()
                                .addHeader("Authorization", "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NDc2OTg1MzgsIm5iZiI6MTU0NzY5NDIxOCwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6InN0cmluZyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6InN0cmluZyIsIkRPQiI6IjEvMTcvMjAxOSIsImlzcyI6InlvdXIgYXBwIiwiYXVkIjoidGhlIGNsaWVudCBvZiB5b3VyIGFwcCJ9.qxFdcdAVKG2Idcsk_tftnkkyB2vsaQx5py1KSMy3fT4")
                            .post<Search, Movie>(url, search);
```

**Comment by VeritasSoftware** [comment]
Hi,

I went ahead and created a npm package **ts-sync-request** for the wrapper.

[**ts-sync-request**](https://www.npmjs.com/package/ts-sync-request)

Maybe you can add a link to the package from your readme.

**Comment by ForbesLindesay** [comment]
Thanks for sharing your library.

I'm not going to link to your client right now, as sync-request is already a typed library. I don't type the request/response bodies because there are no meaningful types you can add. Your call to `.get<Movie>(url);` is equivalent to `.get<any>(url) as Movie;` In this library, we make the `any` implicit and allow you to put the ` as Movie` in yourself. This is safer, in my opinion, because it is clearer from reading the code that there are unsafe casts being used.
