### ISSUE TITLE
Update sync-rpc version in dependencies

### ISSUE THREAD

**Issue by matthewbyrne** [ForbesLindesay/sync-request#109]
https://github.com/ForbesLindesay/sync-rpc/issues/2 outlines a bug which was fixed in sync-rpc v 1.2.3. 
sync-request currently uses 1.2.1. 
Can this be updated, or is this repo not maintained anymore?

**Comment by ForbesLindesay** [comment]
`^1.2.1` includes `1.2.3`. Just delete your lock file and run install again. https://semver.org/

**Comment by matthewbyrne** [comment]
Odd, I his this issue 2 days ago https://github.com/ForbesLindesay/sync-rpc/issues/2
I've only just started using sync-request, so reinstalling isn't going to fix anything.

**Comment by ForbesLindesay** [comment]
In that case:

1. check the actual version of sync-rpc that got installed in your node_modules directory.
2. check you're using the latest version of node

If so, please post the full error & stack trace.
