### ISSUE TITLE
spawnSync fails with ENAMETOOLONG for requests with large payloads

### ISSUE THREAD

**Issue by ThiefMaster** [ForbesLindesay/sync-request#114]
It looks like the whole request data is passed as a command line argument to the worker. Besides the fact that is is quite messy (imagine you send a password in there and it shows up in the process list), it breaks e.g. with payloads >32kB on Windows.

**Comment by ForbesLindesay** [comment]
Please can you check you're running the latest version of this library.  The current version of this library only puts data on the command line when it comes to under `1000` characters, including the js code that wraps it. Beyond that it already uses stdin.  On unix based systems with a valid `nc` command line utility, it uses `stdin` regardless of payload size.

P.S. this issue actually belongs on https://github.com/ForbesLindesay/sync-rpc (assuming you're using the latest version). If you still have further problems, please open an issue on that repository.
