### ISSUE TITLE
Error: spawnSync nc ENOBUFS

### ISSUE THREAD

**Issue by sabbour** [ForbesLindesay/sync-request#119]
On a macOS, this line causes `ENOBUFS` error while downloading a relatively large file

https://github.com/ForbesLindesay/sync-request/blob/d1baeb988d1b37ec6ad8ecb13939b72a267d1719/index.js#L75

Should be changed to 

```js
  var res = spawnSync(command, args, {input: req + '\r\n', maxBuffer: Infinity});
```

**Comment by ForbesLindesay** [comment]
Thanks for reporting this @sabbour. It looks like this was a breaking change in node v12. It's fixed in https://github.com/ForbesLindesay/sync-rpc/pull/8.

**Comment by larshp** [comment]
experiencing same issue, running sync-request 6.1.0 which is the latest, it does not include the fix from sync-rpc
