### ISSUE TITLE
Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by mvliguori** [ForbesLindesay/sync-request#12]
The connection somehow times out and causes an error that causes an exception that crashes.  Not sure if you can make this more graceful.

/opt/node/node_modules/sync-request/index.js:31
    throw new Error(response.error.message || response.error || response);
          ^
Error: connect ETIMEDOUT
    at doRequest (/opt/nodeNexia/node_modules/sync-request/index.js:31:11)
   .....
    at Socket.EventEmitter.emit (events.js:98:17)
    at UDP.onMessage (dgram.js:423:8)

http://stackoverflow.com/questions/23632914/how-to-handle-etimedout-error

**Comment by ForbesLindesay** [comment]
That error should be possible to handle using a try/catch?
