### ISSUE TITLE
sync-rpc breaking Node 6

### ISSUE THREAD

**Issue by larsgw** [ForbesLindesay/sync-request#121]
**I know Node 6 is not supported** anymore, but would it be acceptable to create a version `5.0.1` with the `sync-rpc` version capped at `1.3.4`, since anything higher, automatically installed due to only having a patch version bump, gives the highly confusing error:

>     node: ../deps/uv/src/unix/core.c:182: uv_close: Assertion `0' failed.
>     Aborted

I can try and make a PR, if you want.

**Comment by ForbesLindesay** [comment]
We do now have the `engines.node` set appropriately. Given that node 6 has been dead for several months now (https://nodejs.org/en/about/releases/) I don't really think it merits any effort to provide better errors. This should only be a very short term problem.
