### ISSUE TITLE
Too many open sockets if multiple http calls are made at a time

### ISSUE THREAD

**Issue by bhargav3** [ForbesLindesay/sync-request#13]
I'm writing a custom module and using `sync-request` where it opens 5 sockets at a time. I got the below error which suggests me that there are too many open sockets.

```
child_process.js:948

    throw errnoException(process._errno, 'spawn');
          ^

Error: spawn EMFILE

    at errnoException (child_process.js:1001:11)

    at ChildProcess.spawn (child_process.js:948:11)

    at exports.spawn (child_process.js:736:9)

    at Object.exports.execFile (child_process.js:618:15)

    at Object.exports.exec (child_process.js:589:18)

    at invoke (/home/postman/es-data-migrator/node_modules/sync-request/node_modules/spawn-sync/lib/spawn-sync.js:57:6)

    at spawnSyncFallback (/home/postman/es-data-migrator/node_modules/sync-request/node_modules/spawn-sync/lib/spawn-sync.js:84:3)

    at doRequest (/home/postman/es-data-migrator/node_modules/sync-request/index.js:19:13)

    at esdm.getData (/home/postman/es-data-migrator/src/lib/esdm.lib.js:20:27)

```

**Comment by ForbesLindesay** [comment]
If you can figure out a way to fix this, I'll happily accept a pull request.  I would expect sync-request to open about 5 sockets (doing synchronous io in node is difficult and requires silly dances) but I would expect them to get closed again.  It might be that they are not closed until the next turn of the event loop, so it may not be possible to get code like:

```js
for (var i = 0;  i < 1000000; i++) {
  request('GET', 'http://example.com');
}
```

to work.

One thing you could try is just wrapping it in something like:

```js
function request(method, url, options) {
  try {
    return syncRequest(method, url, options);
  } catch (ex) {
    if (ex.code === 'EMFILE') return request(method, url, options);
    else throw ex;
  }
}
```

if you try that and it works, post back here and we can add that solution to the library.

**Comment by bhargav3** [comment]
Thanks for replying. I was making the HTTP calls to Elasticsearch(ES) server on localhost. Initially I started off with nodejs and needed to find and use synchronous HTTP module which was simple enough to use. I found sync-request but the only issue was this one and used to fail after 550 calls approx and used to crash ES server as well.

I have tried this using php-curl and was able to make 9.5k calls synchronously(obviously) in less than min and the server has crashed so which implies nothing wrong with PHP. I have realized that ES is failing after a repeated HTTP call stack in less time.

**Comment by raeesaa** [comment]
Hi @bhargav3 / @ForbesLindesay Did you find any solution for this issue?

Even I am facing this issue. There are around 26 HTTP GET requests being made in my code. Is there any way I can close the opened sockets before making next HTTP request? I am using this module in production and need to resolve this issue asap. Any help would be greatly appreciated.

**Comment by bhargav3** [comment]
26 calls must be easy to make. Try giving a timeout for about 5s so the open sockets are closed meanwhile.

**Comment by raeesaa** [comment]
Thank you for a quick reply @bhargav3 . Even I feel there should not be any issues for making 26 HTTP requests. The code works fine on my local machine but give an error on production server(Amazon EC2 instance). I'll try to set timeout and let you know if that works.

**Comment by bhargav3** [comment]
Sure and if possible can you send a gist of not-so-confidential part of the code where you are using this module.

**Comment by raeesaa** [comment]
There is no option for setting timeout for this module. Related issue: https://github.com/ForbesLindesay/sync-request/issues/10

**Comment by bhargav3** [comment]
Okay, can you create the gist so I can help you?

**Comment by raeesaa** [comment]
Thank you for your time. I used https://github.com/dhruvbird/http-sync
instead and it is working fine.

Regards,
Raeesaa

**Comment by Vanuan** [comment]
>  so it may not be possible to get code like:
```
for (var i = 0;  i < 1000000; i++) {
  request('GET', 'http://example.com');
}
```

Wow, it exactly why I chose sync version! To limit a number of opened sockets to get rid of EMFILE error! What's the point in that if it isn't possible?
