### ISSUE TITLE
Doesn't work when used in VS Code plugin

### ISSUE THREAD

**Issue by TSMMark** [ForbesLindesay/sync-request#136]
```
find port exited with code 1.
```

**Comment by Trebor-Huang** [comment]
This is fundamentally caused by the fact that `process.execPath` is not `[...]/node`. It is `Code Helper` instead. I think this cannot be used in VSCode. You might want to refactor you code with async functions instead.

**Comment by ForbesLindesay** [comment]
sync-request does not support being used in VSCode Plugins. This is working as intended.
