### ISSUE TITLE
Compliance issue in sync-request 

### ISSUE THREAD

**Issue by ChristineWanjau** [ForbesLindesay/sync-request#139]
We have a compliance issue in ADO caused by the string-decoder library v1.1.1 which the sync-request library depends on.  

Sync-request probably needs to upgrade to v1.3.0 according to https://github.com/nodejs/readable-stream/issues/468

**Comment by Drarig29** [comment]
@ChristineWanjau in case it can help, the `azure-pipelines-task-lib` package removed this dependency: https://github.com/microsoft/azure-pipelines-task-lib/pull/932

So if you are authoring an ADO task, then you can bump `azure-pipelines-task-lib`.

**Comment by ChristineWanjau** [comment]
Thanks that helps!
