### ISSUE TITLE
Jsonp

### ISSUE THREAD

**Issue by artem-malko** [ForbesLindesay/sync-request#17]
Is it possible, to make jsonp request? I have to make request to another domain.

**Comment by ForbesLindesay** [comment]
You can make jsonp requests using https://github.com/then/then-jsonp

It is unfortunately not possible to make synchronous jsonp requests.  You should also keep in mind that synchronous requests are an anti-pattern in any tools that will get frequent use.  It's really only intended for one off scripts and demos.
