### ISSUE TITLE
Nativee thread-sleep not available.

### ISSUE THREAD

**Issue by streamich** [ForbesLindesay/sync-request#18]
How do you disable this message?

    Native thread-sleep not available.
    This will result in much slower performance.
    You should re-install spawn-sync if possible.

**Comment by ForbesLindesay** [comment]
Two options:

1. Upgrade to node@0.12 or iojs
2. Install `try-thread-sleep` as a dependency of your app.  It should get installed automatically, but it gets skipped for some more obscure node + npm setups.

**Comment by streamich** [comment]
Thanks!
