### ISSUE TITLE
Probably caching error: ENOENT, no such file or directory Error: ENOENT, no such file or directory '/var/folders/...'

### ISSUE THREAD

**Issue by tkandal** [ForbesLindesay/sync-request#19]
Hello, Sir

Unfortunately  I keep getting this error when I am using sync-request in my project.

Environment:
$ node -v
v0.10.36
$ uname -a
Darwin host.some.domain 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
$

Parameters to the request:
...
var resourceUrl = util.format(baseUrl, querystring.escape(id));
 var options = {
            gzip: false,
            headers: {
               'some-header': 'some-value'
            }
};
var res = request('GET', resourceUrl, options);
...

This is a straight REST-call with an identifier in the URL,-and the identifier is URL-encoded (as you can see).

fs.js:439
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory '/var/folders/mn/yl6t62f949g6q6ly5b2sk9880000gn/T/spawn-sync_output_28876a1c1303314dc4322934d'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at spawnSyncFallback (/Users/kandal/tmp/git/vendor-integration/node_modules/sync-request/node_modules/spawn-sync/lib/spawn-sync.js:86:27)
    at doRequest (/some/path/node_modules/sync-request/index.js:19:13)

(The name for the temporary file is of course different each time)
Thank You very much.

Trond.

**Comment by adamclerk** [comment]
I'm getting the same error on a long running process.

**Comment by ForbesLindesay** [comment]
The temporary file is used by [spawn-sync](https://github.com/ForbesLindesay/spawn-sync) to communicate with the other process (that actually makes the request).  The best bet would be to update to node v4 which doesn't require that pollyfill.

**Comment by ForbesLindesay** [comment]
We no longer use the spawn-sync polyfill, so this should no longer be an issue.
