### ISSUE TITLE
POST request is not working.. body only contains true

### ISSUE THREAD

**Issue by i2egular** [ForbesLindesay/sync-request#23]
I tried on this code even with JSON.stringify on my data, and tried 
to combine with using and not using option json: true options but it doesn't work.
I've check output request on http://www.posttestserver.com/ , the body contains only 4 letters of 'true'
```
var result = request('POST', testUrl, {
    data : {
      key: publicKey.toString(),
      info: {
        clientName: 'GG',
        adapterUrl: 'https://localhost:3000'
      },
    json: true
  });
```

**Comment by ForbesLindesay** [comment]
Read the docs:

> json - set this to the json you want to send to the server. This will then set the body to JSON representation of value and adds Content-type: application/json. Does not have any affect on how the response is treated.

e.g.

```js
var result = request('POST', testUrl, {
    json : {
      key: publicKey.toString(),
      info: {
        clientName: 'GG',
        adapterUrl: 'https://localhost:3000'
      }
  });
```
