### ISSUE TITLE
GET with request body times out

### ISSUE THREAD

**Issue by zodiac** [ForbesLindesay/sync-request#26]
```
request('GET', 'http://requestb.in/1lhfdlb1', {
  'json': {
    'a': 'b',
  },
});
```

times out for me. (generate a new requestbin url to test)

**Comment by ForbesLindesay** [comment]
This library does not support passing a body to a `'GET'`, `'DELETE'` or `'HEAD'` request.  It would be better if then-request generated a proper error in this instance though.

**Comment by pokatomnik** [comment]
As far as I know, there is no support for a body in HTTP requests you listed. Try to use query string instead.
