### ISSUE TITLE
Issue with SSL

### ISSUE THREAD

**Issue by joshterrill** [ForbesLindesay/sync-request#27]
I'm trying to use `sync-request` on a URL that has SSL enabled and I'm getting the following error: `Error: unable to verify the first certificate`

Has anyone else ran into this?

**Comment by ForbesLindesay** [comment]
You'll get that if node.js doesn't think the server has a valid certificate or if the certificate has expired.  If you have control of the server you should fix the certificate error there, but if all else fails, you can use the solution in #24

**Comment by sunshineo** [comment]
I encountered this because I'm using the free cert from letsencrypt.org
