### ISSUE TITLE
CERT_UNTRUSTED

### ISSUE THREAD

**Issue by rondonjon** [ForbesLindesay/sync-request#28]
I am getting CERT_UNTRUSTED from an https URL.
Is there an (undocumented?) option to skip the certificate check?

**Comment by rondonjon** [comment]
Ah, solved it myself by setting

`process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";`

**Comment by ForbesLindesay** [comment]
Duplicate of #27 and #24.  Please search through old issues before posting a new one.
