### ISSUE TITLE
Request: Have sync-request work with web workers

### ISSUE THREAD

**Issue by JemiloII** [ForbesLindesay/sync-request#29]
I love sync-request! Anyway to have it work with web-workers and function the same while receiving the web worker performance boost?

I been using it in my riotapi project and it's wonderful, just on the frontend, it does the usual freezes due to the nature of xhr sync request.

If you wanted to see how I was using it.
https://github.com/JemiloII/riotapi/blob/master/riotapi/champion/champion.js

`var Lux = champion('Lux'); // makes request and now is json data :)`

**Comment by ForbesLindesay** [comment]
First, let me say that you really should not be using this library in any production applications (or any application where you care about performance).  If you care about performance enough to use a web-worker, you care way too much about performance to justify making synchronous ajax requests.  I've added a note to the readme to try and encourage people not to use this in production.

If you are committed to doing this, it shouldn't actually be too difficult.  All you will need to do is remove the `window.` from https://github.com/ForbesLindesay/sync-request/blob/master/browser.js  I'll accept a pull request if you want to make that change (and test that it works).
