### ISSUE TITLE
Set the website of this GitHub repo to the npm package

### ISSUE THREAD

**Issue by dandv** [ForbesLindesay/sync-request#34]
https://www.npmjs.com/package/sync-request

Example:

[![Adding GitHub repo URL](https://cloud.githubusercontent.com/assets/33569/6536430/76a7d88e-c402-11e4-8883-6ab2c7b8c30a.png)](https://github.com/dandv/meteor-webix)

**Comment by ForbesLindesay** [comment]
I'm not sure that's very useful.  We already link to the npm package from the npm badge in the readme, but there's not really any useful info on the npm package that's not available in the GitHub repo.

**Comment by dandv** [comment]
Download stats. Huge confidence badge.

**Comment by ForbesLindesay** [comment]
Download stats are a generally pretty poor way of choosing a library (e.g. bower is universally known to be a useless waste of software by all experienced node.js developers, but gets downloaded 2 million times a month).  Not quite sure what you mean by "Huge confidence badge" but in general I think this is probably just noise.

Also, if we were going to do this, it would make sense to do it for **all** my npm modules, but I'm not sure if there's any good way of automating this and I'm certainly not adding it manually to ~500 repositories.

**Comment by dandv** [comment]
Fair enough (and [I hate bower too](http://stackoverflow.com/questions/18641899/what-is-the-difference-between-bower-and-npm/31219726#31219726)).

By the confidence badge I was referring to using the number of downloads for competing packages as social proof.
