### ISSUE TITLE
The way to upload file 

### ISSUE THREAD

**Issue by kymtwyf** [ForbesLindesay/sync-request#35]
Hi ,

I am trying to upload file using sync-request. 
Here is my way of uploading(using data as the Buffer to upload)
```
var fs = require('fs');
fs.readFile('to-upload/test.txt', function (err, data) {
    if (err) throw err;
        var resUploadFile = syncRequest('PUT', uploadUrl, {
            data: data
        });
   log(JSON.parse(resUploadFile.statusCode));
});
```
However I failed to upload the file in this way. Can you tell me what's the correct way of uploading files using sync-request.

Thanks!

**Comment by kymtwyf** [comment]
I added the headers options and it works

**Comment by ForbesLindesay** [comment]
Incidentally, `statusCode` is already a number, so you don't need to `JSON.parse` it.

**Comment by kymtwyf** [comment]
yes, you are right ~
