### ISSUE TITLE
making post with multipart/form content-type

### ISSUE THREAD

**Issue by paraplexed** [ForbesLindesay/sync-request#37]
What is the correct way to set the headers/body to be able to make a post request with a multipart/form content-type? I can't figure out where these should go (or where to put them):
```
----Z7depKeH0iSSjand
Content-Disposition: form-data; name="file"; filename="test.csv"
Content-Type: text/csv

----Z7depKeH0iSSjand
Content-Disposition: form-data; name="filename"

test.csv
----Z7depKeH0iSSjand
```
This is what I currently have:
```
    const csv = makeRequest(); // does a GET, stores the csv from that response into a buffer 
    const opts = {
      headers: {
        'Content-Type': 'multipart/form-data; boundary=----Z7depKeH0iSSjand',
        'Accept-Encoding': 'multipart/form-data',
        'X-AUTH-TOKEN': authToken,
      },
      body: csv,
    }
    request('POST', url, opts)
```

**Comment by ForbesLindesay** [comment]
You're probably best off looking at something like https://github.com/form-data/form-data which can do this for you (albeit asynchronously)  It's quite complex and I haven't ever tried to implement it myself.

**Comment by paraplexed** [comment]
Thanks for the suggestion of form-data. For anyone else that runs into this, this worked for me (synchronously):
```
function postCsv(csvBuffer, path) {
  const form = new (require('form-data'))
  const request = require('request')

  form.append('file', csvBuffer)

  const p = new Promise(function(resolve, reject) {
    form.submit({
      // some custom destination settings
      host: getApiHost(),
      port: getApiPort(),
      protocol: getApiProtocol() + ':',
      path: path,
      headers: { 'X-AUTH-TOKEN': auth } // will merge your custom headers with the ones it sets
    }, function(err, res) {
      if(res.statusCode > 300) {
        console.log('Failed to upload csv:')
        console.log(err)
        console.log(res.statusCode())
      }
      resolve()
    })
  })
  return p
}
```

**Comment by ForbesLindesay** [comment]
It's great that the solution worked for you.  For what it's worth, this is not "synchronous" but rather promise based and asynchronous.  This is actually **much** **much** better than doing it synchronously.  See the note in the README:

> You should **not** be using this in a production application. In a node.js application you will find that you are completely unable to scale your server. In a client application you will find that sync-request causes the app to hang/freeze. Synchronous web requests are the number one cause of browser crashes. For production apps, you should use [then-request](https://github.com/then/then-request), which is exactly the same except that it is asynchronous.

You would be much better off using `form-data` for multi-part form uploads and [then-request](https://github.com/then/then-request) for all other requests and just not using sync-request.

**Comment by paraplexed** [comment]
Thanks for the clarification (promise async vs sync). In regards to using then-request instead of sync-request, my use case is for certain testing tasks where I need to run api calls for pre-setup/tear-down of the tests in a very specific order. I decided to use this module instead of then-request so I wouldn't have to worry the a-synchronous-ness of it. (I'd rather spend my time writing the tests than worrying about why api call B ran before api call A during setup)

Just wanted to give some insight on my use case. sync-request works really well for what we're using it for.

**Comment by ForbesLindesay** [comment]
Excellent, that's exactly the right use case for this library.  I am also working on supporting synchronous multi-part form upload so that should be here soon.

**Comment by sbancal** [comment]
Also trying to send POST synchronously for testing purpose ... I've found this discussion matching what I'm looking for, but seems not to have a solution. Do things have changed since Oct 2015?

My aim is do a POST with Cookies and form-data.
I tried the following with no success :

    const request = require('sync-request')
    const FormData = require('form-data')
    let form = new FormData()
    form.append('name', 'Brand new project')
    form.append('description', 'POSTed project description')
    form.append('csrfmiddlewaretoken', csrfToken)
    let res = request('POST', 'http://localhost:9090/api/projects/', {
      headers: {
        Cookie: 'csrftoken=' + csrfCookie + '; sessionid=' + sessionidCookie
      },
      form: form
    })

When capturing this with wireshark, apparently the form is not included.

**Comment by ForbesLindesay** [comment]
You need to use the FormData that comes with `sync-request`:

```js
const request = require('sync-request')
const FormData = request.FormData;

let form = new FormData()
form.append('name', 'Brand new project')
form.append('description', 'POSTed project description')
form.append('csrfmiddlewaretoken', csrfToken)
let res = request('POST', 'http://localhost:9090/api/projects/', {
  headers: {
    Cookie: 'csrftoken=' + csrfCookie + '; sessionid=' + sessionidCookie
  },
  form: form
})
```

**Comment by sbancal** [comment]
Great, that was it! Thanks :+1:

**Comment by adiGitUser** [comment]
Hey @ForbesLindesay can you please help - I still get 415 error on this request -

const request = require('sync-request')
		const FormData = request.FormData;

		let form1 = new FormData()
	        form1.append('grant_type', '*****')
			form1.append('username', '******')
			form1.append('password', '******')
			let res = request('POST', 'https://********healthsuite.com/authorize/oauth2/token', {
			  headers: this.getAppHeaders(), form :form1
			})
			console.log(res)
