### ISSUE TITLE
getBody return Buffer instead of string when no encoding present

### ISSUE THREAD

**Issue by jesusenlanet** [ForbesLindesay/sync-request#41]
Hello,

response.getBody() throws the next error when no encoding is present.
**AssertionError: expected <Buffer 5b 7b 22 ...**

Seeing node Buffer toString method:
*# encoding String, Optional, Default: 'utf8'*

Maybe return this.body.toString() (with utf8 by default) instead of this.body will fix this?

Regards

**Comment by ForbesLindesay** [comment]
`getBody` intentionally returns a `Buffer` when no encoding is specified.  This is to allow you to download images etc.  If you want text, you should specify an encoding of `'utf8'`.

**Comment by mensenvau** [comment]
`res.getBody().toString()`
