### ISSUE TITLE
Error for DELETE

### ISSUE THREAD

**Issue by arpanmukherjee1** [ForbesLindesay/sync-request#43]
Hi,

We get "Socket hangup" as error while trying to execute the below code

```javascript
var res = syncRequest('DELETE', global.packageData.configurationServiceUrl + 'deleteConfig', {
        json: { data: configElement }
    });
    return JSON.parse(res.getBody('utf8'));
```

If we pass ```null``` for the ```bodyContent``` parameter it works fine. Like below:
```javascript
var res = syncRequest('DELETE', global.packageData.configurationServiceUrl + 'deleteConfig', null);
    return JSON.parse(res.getBody('utf8'));
```

Can you suggest the solution to this?

**Comment by ForbesLindesay** [comment]
It's not common practice to send a body with a `DELETE` request, so it is not supported by sync-request.

**Comment by arpanmukherjee1** [comment]
Yes, you are correct, it is not common, but
There exists an external service that we are trying to consume, accepts DELETE body and it's not in our application's control.

Can you please suggest a work-around for this?

**Comment by dandv** [comment]
:+1: Our use case is for the [discourse-api module](https://github.com/dhyasama/discourse-api/blob/master/lib/discourse.js#L167).

Interestingly, that [same discourse-api code](https://github.com/dhyasama/discourse-api/blob/839f72a07f44a5d8e74108d0ab5516caa79fe221/lib/discourse.js) worked [on October 21, 2015](https://github.com/dandv/discourse-post-process/commit/14fe953139bb090cce5bd2140ec39c0058fa3b47).

CC @dhyasama

**Comment by arpanmukherjee1** [comment]
@dandv 
Thanks for the example.
