### ISSUE TITLE
Support for Form params request 

### ISSUE THREAD

**Issue by sriramsantosh** [ForbesLindesay/sync-request#44]
Looks like the library doesn't seem to support a post using form parameters. If it does, can you perhaps provide an example ?

**Comment by ForbesLindesay** [comment]
It doesn't have any built in support.  If you need this, you should start by adding form support to then-request.

**Comment by gunalmel** [comment]
The following worked for me

```
request('POST',
             'https://myserver.com/login',
            {
               headers:{'Content-Type':'application/x-www-form-urlencoded'},
               body:'username=admin&password=admin123'
             }
);
```

**Comment by alowenst** [comment]
Any update on this one? solution by @gunalmel didn't help in my case :/
Thanks

**Comment by ForbesLindesay** [comment]
My comment still stands, if you need this you should add support for it in then-request.
