### ISSUE TITLE
Application freezes when passing 'json' parameter into a 'GET' request

### ISSUE THREAD

**Issue by oegea** [ForbesLindesay/sync-request#54]
Hello!
First of all let me thank you for publishing this library, it is helping us to make some internal-use and testing scripts, that we write using NodeJS.

We observed that if configuration object of a "GET" request includes the "json" property, the script freezes (The script does not resume its work never)  and does not shows any error message.

It would be great if the library showed an error or a warning every time this happens, for making code debugging easier.

**Comment by msepehr** [comment]
Hi,
I like working with your library.
I think I have the same issue. I need to call an API with GET and need to send a json. It freezes a lot of time but finishes with this error : 
```
Error: socket hang up
    at doRequest (c:\Dev\Git\crm\node_modules\sync-request\index.js:31:11)
```
Don't think it is because of json, I think it is about GET + sending BODY.
Any idea?

**Comment by sargant** [comment]
I'm also having the same issue, passing a `json` parameter or a `body` parameter tag to a GET query causes a freeze, which is making working with elasticsearch query DSL impossible.

**Comment by ForbesLindesay** [comment]
Thanks for reporting this, I'm tracking the issue of sending bodies with request methods that don't normally support them in #106.
