### ISSUE TITLE
request failing after a while.

### ISSUE THREAD

**Issue by Ashishjshetty** [ForbesLindesay/sync-request#56]
Hi , i use this module in my web scraper and it works fine for a while but then all requests start failing,
i first thought it may be that the host is blocking but i tried and i could still access the same url that is failing with sync-request. hear is the error i get:
`TypeError: Cannot read property 'toString' of null
    at doRequest (/home/ubuntu/testdir/tvguide/node_modules/sync-request/index.js:27:31)
`

**Comment by ForbesLindesay** [comment]
Looks like spawnSync is returning a `stderr` of `null`.  I can't find anything in the docs that says it should do that (https://nodejs.org/api/child_process.html).  In any case, this must be hiding some underlying error.

**Comment by Ashishjshetty** [comment]
i found the real problem not related to your module sorry, closing it

**Comment by ForbesLindesay** [comment]
If there's something that could have been done in our module to make the error more obvious/easier to spot, we'd love to hear about it.

**Comment by Ashishjshetty** [comment]
After profiling i basically found that system ran out of memory due to memory leak in loadash that was used in cheerio.

**Comment by ForbesLindesay** [comment]
Thanks, probably not much we can do about that.
