### ISSUE TITLE
Json option in request is not resolving variable reference. 

### ISSUE THREAD

**Issue by gokulkr14** [ForbesLindesay/sync-request#58]
I have a Json String saved to a variable jsonString, If i refernce that variable in req object it is not getting resolved. It would be of great help if you can sort out this.

var res = syncRequest('POST', url,
	{
		json: jsonString
	},{
  		'headers': {
			'content-type': 'application/json',
		    'Authorization':'Basic ****',
  		}
	});

**Comment by ForbesLindesay** [comment]
You need to define `jsonString` somewhere.  Also, the `json` option expects an object to be converted into JSON and will set the content-type header automatically.  You do not need to stringing it yourself.
