### ISSUE TITLE
Not working properly when I have an é in the url

### ISSUE THREAD

**Issue by sunshineo** [ForbesLindesay/sync-request#59]
Don't know how is it handled, but what the server side received is wrong.

**Comment by sunshineo** [comment]
And when I have Chinese char in the url too

**Comment by ForbesLindesay** [comment]
If you can build an isolated test case, i can look into it.  Otherwise, I suspect there may be other things causing this.

**Comment by sunshineo** [comment]
@ForbesLindesay Maybe, I completely forgot about filing this ticket. I guess the problem I had went away.
