### ISSUE TITLE
how to get response cookie ??

### ISSUE THREAD

**Issue by smarttang** [ForbesLindesay/sync-request#62]
{ server: 'nginx/1.10.1',
  date: 'Fri, 07 Oct 2016 11:05:18 GMT',
  'content-type': 'text/html',
  'transfer-encoding': 'chunked',
  connection: 'close',
  'x-powered-by': 'PHP/5.5.31',
  'set-cookie': 
   [ 'ci_session=a%3A5%3A%7Bs%3A10%3A%22session_id%22%3Bs%3A32%3A%22cfd30f3790c9c54a3a37d59a31e964a3%22%3Bs%3A10%3A%22ip_address%22%3Bs%3A9%3A%22127.0.0.1%22%3Bs%3A10%3A%22user_agent%22%3Bb%3A0%3Bs%3A13%3A%22last_activity%22%3Bi%3A1475838318%3Bs%3A9%3A%22user_data%22%3Bs%3A0%3A%22%22%3B%7D0bd06711d12f305a41296c637a0d670c510dcf07; expires=Fri, 07-Oct-2016 13:05:18 GMT; Max-Age=7200; path=/',
     'ci_session=a%3A6%3A%7Bs%3A10%3A%22session_id%22%3Bs%3A32%3A%22cfd30f3790c9c54a3a37d59a31e964a3%22%3Bs%3A10%3A%22ip_address%22%3Bs%3A9%3A%22127.0.0.1%22%3Bs%3A10%3A%22user_agent%22%3Bb%3A0%3Bs%3A13%3A%22last_activity%22%3Bi%3A1475838318%3Bs%3A9%3A%22user_data%22%3Bs%3A0%3A%22%22%3Bs%3A8%3A%22username%22%3Bb%3A0%3B%7D86252f436517ca9d65c812f9ebee93ea137123b6; expires=Fri, 07-Oct-2016 13:05:18 GMT; Max-Age=7200; path=/' ] }

response have "set-cookie", I login in for php and have a session,than, I want get cookie.how can i get response cookie?

**Comment by ForbesLindesay** [comment]
Handling cookies is out of scope for this library.  It will provide the necessary headers if you want to build your own cookie-jar implementation though.
