### ISSUE TITLE
Basic GET request is sending Content-Length header

### ISSUE THREAD

**Issue by semaja2** [ForbesLindesay/sync-request#65]
Hi,

I am trying to replace a normal request with a sync-request, however when I try to retrieve the body of a URL, the webserver is rejecting it due to 'Content-Length: 0' being in the header

GET /uploaded_files/holidayCalendar.ics HTTP/1.1
Content-Length: 0
Host: www.safework.sa.gov.au
Connection: close

Without the Content-Length being defined the server is happy to send a response, however with it in the request, it see it as malformed and drops the request

Andrew

**Comment by 7macaw** [comment]
Yes, this breaks some servers and I can use the library because of this :(

**Comment by ForbesLindesay** [comment]
Please submit a pull request to then-request, which should automatically resolve the problem in this library.
