### ISSUE TITLE
can't do an upload request with form-data module

### ISSUE THREAD

**Issue by moyuyc** [ForbesLindesay/sync-request#67]
multipart/form-data

**Comment by ForbesLindesay** [comment]
No.  If you want to add support for this, you'll first need to add support to [then-request](https://github.com/then/then-request) via a pull request (which I will happily accept).  Once it's been added to then-request, it will be pretty easy to extend support to sync-request.  I don't personally need it though, so I won't build it unless someone either contributes, or pays me to do it :)
