### ISSUE TITLE
Issue with v2.0.0

### ISSUE THREAD

**Issue by brandonb927** [ForbesLindesay/sync-request#7]
There seems to be a bit of an issue with 2.0.0, or maybe it's just me.

![image](https://cloud.githubusercontent.com/assets/1509352/6162846/390cd2c0-b23e-11e4-800f-d4b598807b89.png)

I'm using v0.12.0 of node.js, but the same thing happens on v0.10.36.

**Comment by salerat** [comment]
Yes, the same, quick fix please

**Comment by ForbesLindesay** [comment]
Sorry about this.  I accidentally added some console.log calls to `http-basic` which this module depends on.  If you delete your node_modules folder and then re-install it should be fixed.

Please close this issue once you have tested the fix :)

**Comment by brandonb927** [comment]
Reinstall, all good!
