### ISSUE TITLE
Post not responding in the same way as curl

### ISSUE THREAD

**Issue by philipacrowe** [ForbesLindesay/sync-request#70]
Posting sync-request doesn't seem work the same as curl. Get requests work fine. The endpoint definitely works as i can curl it with the same body/header, but with sync-request I get "{"detail":"Unsupported media type \"\" in request."}" error.

Curl command that works:
curl --header "Authorization:Token ' + token + '" -d "' + bodyObj + '" ' + root + '/mobile/endpoint/'

sync-request that doesnt work:

    var resPost = request('POST', root + '/mobile/endpoint/', {
      	headers: {
        	'Authorization': "Token " + token,
        	'Content-Type': 'application/json'
      	},
    	body: bodyObj
    });

**Comment by ForbesLindesay** [comment]
Curl will tend to send arbitrary extra headers by default.  sync-requests aims to be a much more bare-bones request library, and generally only sends the headers you ask it to.  You can see the differences in the requests that get sent via a service like requestbin, and then you should be able to add whatever headers you need.
