### ISSUE TITLE
Always displays the "NC" warning message

### ISSUE THREAD

**Issue by ghost** [ForbesLindesay/sync-request#71]
The "NC" warning message displays even after I installed netcat and verified that typing "nc" in the terminal works.

**Comment by turbopope** [comment]
I've got the same problem in Ubuntu 16.10. I've tried both the `nc` from the **netcat-openbsd** package and from the **netcat-traditional** package.

**Comment by maciek134** [comment]
It checks for `nc`'s availability in a weird way - looking for `hostname` in result of `nc --help`. There are two things wrong with that: the command for help is `nc -help` (at least for **netcat-openbsd**) and hostname is nowhere to be found in there. Changed _index.js:32-33_ to:
```
const result = spawnSync('nc', ['-help']);
if (result.stderr && result.stderr.toString('utf8').indexOf('netcat') !== -1) {
```
and seems to be working.
