### ISSUE TITLE
What is nc used for?

### ISSUE THREAD

**Issue by domenic** [ForbesLindesay/sync-request#75]
I think this project would benefit from documentation on what it uses nc for. (I don't know what nc is, besides something that will cause a warning for my users if I don't have it installed.)

I couldn't really figure it out from looking at the code.

(Context: thinking about using this in jsdom, to help with https://github.com/tmpvar/jsdom/issues/1833)

**Comment by mikesherov** [comment]
https://en.m.wikipedia.org/wiki/Netcat

**Comment by ForbesLindesay** [comment]
If we implemented what we need from netcat in node.js it would look something like:

```js
const port = process.argv[2];
process.stdin.pipe(require('net').connect(port).pipe(process.stdout);
```

Loading node with an http/https library takes around 200ms. You don't want to pay that cost in every request, so we spawn one such worker on startup.

Spawning netcat and serialising the request and sending that request over to the worker process only takes about 2ms.

Even using this node polyfill would only add around 50ms, so still much more efficient than a worker per request.

If you feel like writing this up as an appendix to the read me or something, that would be awesome (I'm on my phone at the moment).

Also, I guess we should make the warning link to a proper explanation.

**Comment by domenic** [comment]
Awesome, thanks for explaining. The Wikipedia article wasn't very helpful, but I guess the upside is "netcat allows sync IPC".

What would make this module ideal for jsdom is an option to turn off the warning. I don't want users of jsdom to see this; using sync XHR is known to be slow and bad practice, so hopefully it's just because they're scraping a badly-behaved website, which will be outside their control.

Also of course adding the 50 ms Node polyfill would be even nicer.

**Comment by ForbesLindesay** [comment]
I'd be happy to accept a pull request for either/both :)

I think "we can abuse netcat for sync IPC" would probably be an accurate summary :)

**Comment by domenic** [comment]
Awesome. It might be a while before I get around to it, as first I need to rearchitect jsdom's sync XHR implementation to work on top of this (instead of spawning a worker which just runs all of jsdom's sync XHR implementation every time). But if/when I get that working, I'll be back!!

**Comment by ForbesLindesay** [comment]
Feel free to ping me on twitter if I seem like I might have lost the notification in the deluge of e-mail.

**Comment by ForbesLindesay** [comment]
I extracted the code for fast, synchronous RPC into https://github.com/ForbesLindesay/sync-rpc and dropped the warning message, since I felt it was too noisy for something that is just a small overhead and seems to be totally impossible for you to do anything about anyway.
