### ISSUE TITLE
CORS request doesn't send cookies

### ISSUE THREAD

**Issue by benjefferies** [ForbesLindesay/sync-request#79]
I am making a request where I need to pass the cookies for the current domain to another domain i.e. CORS request. Currently cookies aren't sent when making CORS requests.

The scenario:

I am on `https://example.com` and I make a request
```
    syncRequest('GET', 'https://api.example.com')
```
This leads to a 401 unauthorised because the cookie isn't sent.

I believe the underlying request is made using XMLHttpRequest. Some [documentation](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials) suggests you can include cookies when making CORS requests by setting `XMLHttpRequest.withCredentials = true`.

**Comment by ForbesLindesay** [comment]
You should not use sync-request for browser based applications due to the performance issues.  If you want to fix this, I suggest sending a pull request to https://github.com/then/then-request with the appropriate changes. Those changes can then be integrated into sync-request afterwards.
