### ISSUE TITLE
 throw new Error(res.stderr.toString())

### ISSUE THREAD

**Issue by Messiahhh** [ForbesLindesay/sync-request#81]
I use sync-request to send lots of sync request. But after i send part of them,my app crash.
![image](https://user-images.githubusercontent.com/22492458/28578798-57e17b90-718d-11e7-92cc-bbdcd32ba5ab.png) just like this

**Comment by Messiahhh** [comment]
I've seen the source where 'res.stderr.toString' is.It seems that the res.status !== 0,what's that means?

**Comment by ForbesLindesay** [comment]
It means that the background worker that is sending the requests has crashed. I don't know what could be causing this.

**Comment by Fly-Style** [comment]
Same story, Node 8.9

**Comment by ForbesLindesay** [comment]
Could you try using the new version. I've not done anything that I specifically expect to have fixed your issue, but a lot has been re-written, so it's possible things will have resolved themselves.

**Comment by biolauri** [comment]
I stumbled upon the same problem with the latest version (5.0.0) but with a slightly different error message:
> ```
> node_modules/sync-rpc/lib/index.js:124
>          res.stdout.toString() +
>                    ^
>
> TypeError: Cannot read property 'toString' of null
>    at sendMessage (node_modules/sync-rpc/lib/index.js:124:21)
>    at node_modules/sync-rpc/lib/index.js:154:25
>    at request (node_modules/sync-request/lib/index.js:28:15)
> […]
> ```
I assume that it's the same error.

@ForbesLindesay, do you have any guess on this?

**Comment by ForbesLindesay** [comment]
@biolauri thanks for this report, that was really helpful. could you try it out with version 1.3.3 (just released) of sync-rpc and let me know if you get a more helpful error.

**Comment by biolauri** [comment]
I just updated both dependencies (sync-request@6.0.0 and sync-rpc@1.3.3) and the error above is gone, but I stumble upon a new error:
> ```
> node_modules/sync-rpc/lib/index.js:122
>      throw res.error;
>      ^
>
> Error: spawnSync
> /var/jenkins_home/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/Default/bin/node E2BIG
>    at exports._errnoException (util.js:1050:11)
>    at spawnSync (child_process.js:459:20)
>    at Object.nodeNC [as fastestFunction] (node_modules/sync-rpc/lib/index.js:94:10)
>    at sendMessage (node_modules/sync-rpc/lib/index.js:113:29)
>    at node_modules/sync-rpc/lib/index.js:154:25
>    at request (node_modules/sync-request/lib/index.js:28:15)
> [...]
> ```

I'm just guessing, as it seems to be similar to shelljs/shelljs#819: Maybe the input *input* is too large for (our specific) OS and we're exceeding the maximum OS size limit on command line parameters , so it might be better to pass it as a file. But, again, I'm just guessing blindly.

**Comment by ForbesLindesay** [comment]
Thanks @biolauri. That definitely was an issue, and I never would have spotted it without your help. It should be fixed by sync-rpc 1.3.4. Let me know if there are still issues. I really think this one might have fixed it.

**Comment by ForbesLindesay** [comment]
@biolauri That doesn't look like an issue that's specific to sync-request. That looks like it's just a problem with certificates on the server you are communicating with. https://github.com/nodejs/help/issues/979 offers some general advice for self-signed certificates. I'm going to close this as it looks like the original issue has been resolved.

**Comment by henryfw** [comment]
Add 

    process.env["NODE_TLS_REJECT_UNAUTHORIZED"] = 0;
