### ISSUE TITLE
POST request doesn't work

### ISSUE THREAD

**Issue by labo28** [ForbesLindesay/sync-request#85]
Posting sync-request doesn't seem work. Get requests work fine.
Code:

`var res = request('POST',url , { 'headers': { authorization: 'Basic ' + Buffer(username + ':' + password, 'ascii').toString('base64') } body: postJson2, json: true } );`

As a failure message comes at 'body' --> unexpected identifier.
Can someone find the mistake and give me a solution ?

**Comment by ForbesLindesay** [comment]
```js
var res = request('POST',url , { 'headers': { authorization: 'Basic ' + Buffer(username + ':' + password, 'ascii').toString('base64') }, json: postJson2 } );
```

If you want to post json data, you have to pass that data in the json parameter.  the `body` parameter must always be a string or Buffer
