### ISSUE TITLE
Better documentation for options

### ISSUE THREAD

**Issue by bluepuma77** [ForbesLindesay/sync-request#9]
It would be great to have more info about the options and how to use them.

I assumed the json option can be set to true and I tried
```
var request = require('sync-request');
var res = request('GET', 'http://example.com', {'json': true});
console.log(res);
```
but the json:true doesn't work for me. Maybe the current documentation can be improved:

> json - sets body but to JSON representation of value and adds Content-type: application/json. 
> Does not have any affect on how the response is treated.

**Comment by sam2332** [comment]
is the developer even working on this anymore?
im interested in what you discovered about this! 

i need a sync json request lib

**Comment by icyflame** [comment]
@sam2332 

This library does work, but I am not sure why there has been no reply on this issue.

(That line in the documentation is actually too confusing, I am not even sure it makes sense!)

***

/ @ForbesLindesay

**Comment by ForbesLindesay** [comment]
@sam2332 this library is essentially finished.  I don't have any intention of adding new features because it is stable.

As for the documentation, the options are passed through to then-request.  I'll happily take pull requests for updated documentation.
