### ISSUE TITLE
How to upload file as binary? Not form

### ISSUE THREAD

**Issue by sunshineo** [ForbesLindesay/sync-request#95]
Hello, I'm uploading to a parse server, the following curl command works
```
curl -X POST \
  -H "X-Parse-Application-Id: my-app" \
  -H "Content-Type: video/mp4" \
  --data-binary @my-video.mp4 \
  https://my-parse-host.com/parse/files/video-file
```
I could not figure out how to do this using sync-request
Please help. Thanks

**Comment by ForbesLindesay** [comment]
data-binary is just the default when using sync-request. Just call `request('POST', 'https://my-parse-host.com/parse/files/video-file', {body: fs.readFileSync('my-video.mp4'), headers: {'Content-Type': 'video/mp4'}})`

**Comment by sunshineo** [comment]
Thank you very much!. I must have passed in body and headers as 2 separated arguments. I think it's the axios habit. I'll try this and report back
