### ISSUE TITLE
Documentation could acknowledge that it's OK to use this in conjunction with shelljs

### ISSUE THREAD

**Issue by boutell** [ForbesLindesay/sync-request#98]
I get why you'd not use this in production in a traditional node server app, but a production shell script replacement is another story. Folks use shelljs synchronously all the time in those, and are probably even using it to invoke `curl` for lack of this module (: It might be worth mentioning in the README's warning that it's acceptable in that context.

**Comment by boutell** [comment]
(Thanks for the module!)

**Comment by ForbesLindesay** [comment]
Perhaps you could submit a pull request with a proposed clarification. The wording in the readme is as forceful as it is because I know a large number of people **do** abuse this module by using it directly in production node.js apps.
